# Generated by Django 4.0.4 on 2022-08-19 03:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_delete_page_alter_photographerhires_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 3, 48, 30, 521856, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='PhotographerHires',
        ),
    ]
