# Generated by Django 4.0.4 on 2022-08-19 03:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographerHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing', models.IntegerField(default=0)),
                ('pricing_period', models.CharField(max_length=25, null=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2022, 8, 19, 3, 48, 30, 571138, tzinfo=utc), verbose_name='Start date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2022, 8, 19, 3, 48, 30, 571138, tzinfo=utc), verbose_name='End date')),
                ('rating', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
