# Generated by Django 4.0.4 on 2022-07-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_authtoken_user_authtype_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Authtoken',
            new_name='auth_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='authType',
            new_name='auth_type',
        ),
    ]
