# Generated by Django 4.0.4 on 2022-07-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_auth_code_alter_user_auth_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='auth_code',
            new_name='auth_status',
        ),
    ]
