# Generated by Django 4.0.4 on 2022-07-25 02:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_token_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 2, 9, 51, 125804, tzinfo=utc), verbose_name='date published'),
        ),
    ]
