# Generated by Django 4.0.4 on 2022-07-29 04:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_password_alter_user_token_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['rating']},
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='0', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='photographer',
            field=models.IntegerField(choices=[(0, 'Not a Photographer'), (1, 'A Photographer')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pricing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pricing_period',
            field=models.CharField(default='0', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(default='0', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='town',
            field=models.CharField(default='0', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='workday_end',
            field=models.CharField(default='0', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='workday_start',
            field=models.CharField(default='0', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 4, 46, 28, 990495, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='PhotoUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ManyToManyField(to='users.photo')),
            ],
        ),
        migrations.CreateModel(
            name='PhotographerHires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=25)),
                ('pricing', models.IntegerField(default=0)),
                ('pricing_period', models.CharField(max_length=25)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2022, 7, 29, 4, 46, 28, 990495, tzinfo=utc), verbose_name='Start date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2022, 7, 29, 4, 46, 28, 990495, tzinfo=utc), verbose_name='End date')),
                ('rating', models.IntegerField(default=0)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
