# Generated by Django 4.0.4 on 2022-08-04 03:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_photographerhires_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='photographerhires',
            name='client_id',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='photographerhires',
            name='client',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='users.photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photographerhires',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 3, 44, 12, 410545, tzinfo=utc), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='photographerhires',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 3, 44, 12, 410545, tzinfo=utc), verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 3, 44, 12, 407545, tzinfo=utc), verbose_name='date published'),
        ),
    ]
